fs/sdfat: guard sdfat_debug_warn_on behind ONFIG_SDFAT_DEBUG
Disabling CONFIG_SDFAT_DEBUG causes error because it has hardcoded sdfat_debug_warn_on. To resolve this simply guard this behind a #ifdef block.

Resolves error:

../fs/sdfat/blkdev.c:176:3: error: implicit declaration of function 'sdfat_debug_warn_on' [-Werror,-Wimplicit-function-declaration]
                sdfat_debug_warn_on(1);
                ^
../fs/sdfat/blkdev.c:230:3: error: implicit declaration of function 'sdfat_debug_warn_on' [-Werror,-Wimplicit-function-declaration]
                sdfat_debug_warn_on(1);
                ^
2 errors generated.

Signed-off-by: AKM <akmabrar04@gmail.com>